"""new fields in user model

Revision ID: 8482417040b6
Revises: b2e0877db71c
Create Date: 2024-11-20 16:30:36.840784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8482417040b6'
down_revision = 'b2e0877db71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
